### ISSUE TITLE
HW3

### ISSUE THREAD

**Issue by apogadaev** [dddobriak/loftschool-third-week#1]
- https://github.com/dddobriak/loftschool-third-week/blob/main/composer.json#L6 для корректной работы приложения не хватает ext-pdo
 - не замечание а good practice - в современных проектах чаще всего используется типизация - тем самым мы решаем кучу головной боли в поисках ошибок постарайся внести типизацию (type-hint, типы возвращаемых значений итд) https://github.com/dddobriak/loftschool-third-week/blob/main/app/Models/DbConnect.php#L11 (тут например должен быть указан тип PDO)
 - Миграции не являются моделью, это вспомогательный элемент который вообще не должен находится на app/ слое
 - Коннект к бд это не сама модель а часть модели. Вынеси конект в трейт и используй его в настоящих моделях для подключения к бд.
 - Модель юзера без свойств это не модель, а скорее просто какой-то менеджер для работы с базой данных. У модели должны быть свойства `name`, `email`, `password` которые сетятся при создании модели из полученных по апи данных. Данные из запроса -> Модель -> Таблица в бд. А сейчас у тебя Данные из запроса -> Таблица в БД. - то же самое с моделью поста

**Comment by dddobriak** [comment]
привет, новая версия со всеми исправлениями + задание 4й недели: https://github.com/dddobriak/loftschool-fourth-week
